# Generated by Django 5.2.1 on 2025-05-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workTest', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ad',
            name='condition',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ad',
            name='created_at',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ad',
            name='description',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ad',
            name='image_url',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ad',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ad',
            name='user',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='exchangeproposal',
            name='ad_receiver',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='exchangeproposal',
            name='ad_sender',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='exchangeproposal',
            name='comments',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='exchangeproposal',
            name='created_at',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='exchangeproposal',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
