# Generated by Django 5.2.1 on 2025-05-21 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workTest', '0003_ad_category_ad_condition_ad_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
