# Generated by Django 5.2.1 on 2025-05-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workTest', '0004_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='created_at',
            field=models.DateTimeField(default='', max_length=20),
        ),
    ]
