# Generated by Django 5.2.1 on 2025-06-01 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workTest', '0010_exchangeproposal_offered_item_alter_ad_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeproposal',
            name='desired_item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='desired_item', to='workTest.ad'),
        ),
    ]
