# Generated by Django 5.2.1 on 2025-06-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workTest", "0013_alter_exchangeproposal_ad_receiver_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="description",
            field=models.CharField(default="", max_length=200),
        ),
    ]
