# Generated by Django 5.2.1 on 2025-06-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workTest", "0014_alter_ad_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="exchangeproposal",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
